{
	"id": "CVE-2021-46823",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-46823",
				"description": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
				"references": [
					{
						"source": "mitre",
						"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/221507"
					},
					{
						"source": "mitre",
						"url": "https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm"
					}
				]
			}
		}
	],
	"data_source": "mitre-v5"
}
