{
	"id": "CVE-2020-29651",
	"vulnerabilities": [
		{
			"id": "CVE-2020-29651",
			"description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
			"references": [
				{
					"source": "mitre",
					"url": "https://github.com/pytest-dev/py/issues/256"
				},
				{
					"source": "mitre",
					"url": "https://github.com/pytest-dev/py/pull/257"
				},
				{
					"source": "mitre",
					"url": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
				},
				{
					"source": "mitre",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AYWNYEV3FGDHPIHX4DDUDMFZ6NLCQRC4/"
				},
				{
					"source": "mitre",
					"url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/CHDTINIBJZ67T3W74QTBIY5LPKAXEOGR/"
				},
				{
					"source": "mitre",
					"url": "https://www.oracle.com/security-alerts/cpujul2022.html"
				}
			]
		}
	],
	"data_source": "mitre-v5"
}
