{
	"id": "CVE-2018-11499",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2018-11499",
				"description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact.",
				"references": [
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00047.html"
					},
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00051.html"
					},
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00027.html"
					},
					{
						"source": "CVE",
						"url": "https://github.com/sass/libsass/issues/2643"
					},
					{
						"source": "mitre",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00047.html"
					},
					{
						"source": "mitre",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00051.html"
					},
					{
						"source": "mitre",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00027.html"
					},
					{
						"source": "mitre",
						"url": "https://github.com/sass/libsass/issues/2643"
					}
				],
				"modified": "2024-08-05T08:10:14.837Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2018/CVE-2018-11499.json"
		]
	}
}
