{
	"id": "CVE-2018-1000807",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2018-1000807",
				"description": "Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0.",
				"references": [
					{
						"source": "CVE",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2019:0085"
					},
					{
						"source": "CVE",
						"url": "https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509"
					},
					{
						"source": "CVE",
						"url": "https://github.com/pyca/pyopenssl/pull/723"
					},
					{
						"source": "CVE",
						"url": "https://usn.ubuntu.com/3813-1/"
					},
					{
						"source": "mitre",
						"url": "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
					},
					{
						"source": "mitre",
						"url": "https://access.redhat.com/errata/RHSA-2019:0085"
					},
					{
						"source": "mitre",
						"url": "https://github.com/pyca/pyopenssl/commit/e73818600065821d588af475b024f4eb518c3509"
					},
					{
						"source": "mitre",
						"url": "https://github.com/pyca/pyopenssl/pull/723"
					},
					{
						"source": "mitre",
						"url": "https://usn.ubuntu.com/3813-1/"
					}
				],
				"modified": "2024-08-05T12:47:56.674Z"
			}
		}
	],
	"data_source": "mitre-v5"
}
