{
	"id": "CVE-2024-3657",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2024-3657",
				"title": "389-ds-base: potential denial of service via specially crafted kerberos as-req request",
				"description": "A flaw was found in 389-ds-base. A specially-crafted LDAP query can potentially cause a failure on the directory server, leading to a denial of service",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "redhat",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
							"base_score": 7.5,
							"base_severity": "HIGH",
							"temporal_score": 7.5,
							"temporal_severity": "HIGH",
							"environmental_score": 7.5,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "redhat",
						"cwe": [
							"CWE-20"
						]
					}
				],
				"references": [
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:3591"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:3837"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:4092"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:4209"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:4210"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:4235"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/errata/RHSA-2024:4633"
					},
					{
						"source": "CVE",
						"url": "https://access.redhat.com/security/cve/CVE-2024-3657"
					},
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274401"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:3591"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:3837"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:4092"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:4209"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:4210"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:4235"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:4633"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/errata/RHSA-2024:5690"
					},
					{
						"source": "redhat",
						"url": "https://access.redhat.com/security/cve/CVE-2024-3657"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274401"
					}
				],
				"published": "2024-05-28T12:53:03.399Z",
				"modified": "2024-08-21T12:18:25.266Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2024/CVE-2024-3657.json"
		]
	}
}
