{
	"id": "CVE-2015-3220",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2015-3220",
				"description": "The tlslite library before 0.4.9 for Python allows remote attackers to trigger a denial of service (runtime exception and process crash).",
				"references": [
					{
						"source": "CVE",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1254215"
					},
					{
						"source": "CVE",
						"url": "https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853"
					},
					{
						"source": "CVE",
						"url": "https://groups.google.com/forum/#%21topic/tlslite-dev/MoWE7B0A4iU"
					},
					{
						"source": "redhat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1254215"
					},
					{
						"source": "redhat",
						"url": "https://github.com/trevp/tlslite/commit/aca8d4f898b436ff6754e1a9ab96cae976c8a853"
					},
					{
						"source": "redhat",
						"url": "https://groups.google.com/forum/#%21topic/tlslite-dev/MoWE7B0A4iU"
					}
				],
				"modified": "2024-08-06T05:39:32.027Z"
			}
		}
	],
	"data_source": {
		"id": "mitre-v5",
		"raws": [
			"vuls-data-raw-mitre-v5/2015/CVE-2015-3220.json"
		]
	}
}
