{
	"id": "CVE-2015-3206",
	"vulnerabilities": [
		{
			"id": "CVE-2015-3206",
			"description": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack.",
			"references": [
				{
					"source": "redhat",
					"url": "http://www.openwall.com/lists/oss-security/2015/05/21/3"
				},
				{
					"source": "redhat",
					"url": "http://www.securityfocus.com/bid/74760"
				},
				{
					"source": "redhat",
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802"
				},
				{
					"source": "redhat",
					"url": "https://github.com/apple/ccs-pykerberos/issues/31"
				},
				{
					"source": "redhat",
					"url": "https://pypi.python.org/pypi/kerberos"
				}
			]
		}
	],
	"data_source": "mitre-v5"
}
