{
	"id": "CVE-2022-41887",
	"vulnerabilities": [
		{
			"id": "CVE-2022-41887",
			"title": "Overflow in `tf.keras.losses.poisson` in Tensorflow",
			"description": "TensorFlow is an open source platform for machine learning. `tf.keras.losses.poisson` receives a `y_pred` and `y_true` that are passed through `functor::mul` in `BinaryOp`. If the resulting dimensions overflow an `int32`, TensorFlow will crash due to a size mismatch during broadcast assignment. We have patched the issue in GitHub commit c5b30379ba87cbe774b08ac50c1f6d36df4ebb7c. The fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1 and 2.9.3, as these are also affected and still in supported range. However, we will not cherrypick this commit into TensorFlow 2.8.x, as it depends on Eigen behavior that changed between 2.8 and 2.9.",
			"severity": [
				{
					"type": "cvss_v31",
					"source": "GitHub_M",
					"cvss_v31": {
						"vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:N/A:H",
						"base_score": 4.8,
						"base_severity": "MEDIUM",
						"temporal_score": 4.8,
						"temporal_severity": "MEDIUM",
						"environmental_score": 4.8,
						"environmental_severity": "MEDIUM"
					}
				}
			],
			"cwe": [
				{
					"source": "GitHub_M",
					"cwe": [
						"CWE-131"
					]
				}
			],
			"references": [
				{
					"source": "GitHub_M",
					"url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_ops_common.h"
				},
				{
					"source": "GitHub_M",
					"url": "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/losses.py"
				},
				{
					"source": "GitHub_M",
					"url": "https://github.com/tensorflow/tensorflow/commit/c5b30379ba87cbe774b08ac50c1f6d36df4ebb7c"
				},
				{
					"source": "GitHub_M",
					"url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-8fvv-46hw-vpg3"
				}
			]
		}
	],
	"data_source": "mitre-v5"
}
